### ISSUE TITLE
VK longpolling

### ISSUE THREAD

**Issue by vladwix** [unam3/trial-bot-all#3]
Из [дока](https://vk.com/dev/bots_longpoll)
> В ответ на запрос сервер может вернуть одну из ошибок:
{"failed":1,"ts":30}
{"failed":2}
{"failed":3}
"failed":1 — история событий устарела или была частично утеряна, приложение может получать события далее, используя новое значение ts из ответа.
"failed":2 — истекло время действия ключа, нужно заново получить key методом groups.getLongPollServer.
"failed":3 — информация утрачена, нужно запросить новые key и ts методом groups.getLongPollServer.
Обратите внимание, объекты в сообщении об ошибке могут содержат поля, не описанные в документации. Их необходимо игнорировать и не пытаться обработать.

По хорошему эти кейсы надо обрабатывать

**Comment by unam3** [comment]
@vladwix take a look at https://github.com/unam3/trial-bot-all/commit/7c6d28c7f6e8f540d4e473ea4057972b9631e49e

**Comment by vladwix** [comment]
Is this `failed` field set anywhere?

**Comment by unam3** [comment]
https://github.com/unam3/trial-bot-all/blob/7c6d28c7f6e8f540d4e473ea4057972b9631e49e/src/Vk.hs#L83-L96 here we check if the server reply has this field.

**Comment by vladwix** [comment]
Oh, looks like I overlooked this part
