### ISSUE TITLE
Разделить стейт и статическое окружение

### ISSUE THREAD

**Issue by vladwix** [unam3/trial-bot-all#4]
Сейчас `Config` телеги (который, вообще-то стейт)
```
data Config =
  Config
    { tokenSection :: TokenSection
    , helpMessage :: HelpMessage
    , repeatMessage :: RepeatMessage
    , numberOfRepeats :: NumberOfRepeats
    , numberOfRepeatsMap :: NumberOfRepeatsMap
    }
```
содержит в себе два типа полей: статические, которые не меняются во время выполнения: `repeatMessage`, `helpMessage`, `tokenSection`, `NumberOfRepeats`. И динамический `numbersOfRepeatsMap`. Совмещать в одном типе данных две разные штуки -- стейт и статическое окружение не стоит, если в этом нет необходимости.

Обычно для хранения окружения используют `ReaderT`, а для состояния либо `StateT` либо в ридер кладут `MVar`, `TVar` или `IORef`, но можно и просто передавать аргументом ф-ии

Тоже самое относится к "конфигу" вк

**Comment by unam3** [comment]
@vladwix done
