### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by vladwix** [unam3/trial-bot-all#5]
* Использование нетотальных ф-ий (тех которые могут вывалится с рантайм ошибкой) крайне желательно избегать. В коде достаточно много используется `fromJust`. В случае `init`, `head` лучше использовать деконструкцию списка
* В целом отсутствует обработка ошибок. Если выпадет ексепшн по любому поводу у всего приложения большие шансы закрашиться. Для обработки ошибок можно использовать разные подходы: `ExceptT`, `catch`/`try`, явный возврат `Maybe`/`Just`. Каждую ошибку хорошо бы логгировать в собственном логгере с уровнем error

**Comment by unam3** [comment]
> В случае `init`, `head` лучше использовать деконструкцию списка
В коде не используются init и head.

**Comment by unam3** [comment]
> * Использование нетотальных ф-ий (тех которые могут вывалится с рантайм ошибкой) крайне желательно избегать. В коде достаточно много используется `fromJust`.

Убрал, где необходимо. Оставил, где поля в доках идут вместе с другими и "обязательны".

> * В целом отсутствует обработка ошибок. Если выпадет ексепшн по любому поводу у всего приложения большие шансы закрашиться. Для обработки ошибок можно использовать разные подходы: `ExceptT`, `catch`/`try`, явный возврат `Maybe`/`Just`. Каждую ошибку хорошо бы логгировать в собственном логгере с уровнем error

Где именно необходимо обрабатывать и какие ошибки? Все на Maybe/Either, что препдологает возможность обработки.

**Comment by vladwix** [comment]
> В коде не используются init и head.

Да, это просто пример полезных, но нетотальных ф-й
> Убрал, где необходимо. Оставил, где поля в доках идут вместе с другими и "обязательны".

Так все равно не стоит делать, лучше продумать систему типов, например, имея тип
```
data A a = A
  { "ok" :: Bool
  , "response" :: Maybe a
  , "error" :: Maybe Error
  }
```
в котором от поля `ok` зависит что "обязательно" будет, лучше рассмотреть другие модели, например:
```
data A a = Success a | Failure Error
instance FromJSON (A a) where 
  parseJSON = withObject $ \v -> do
    ok <- v .: "ok"
    if ok then Success <$> v .: "response"
    else Failure <$> v .: "error"
```

**Comment by vladwix** [comment]
> Где именно необходимо обрабатывать и какие ошибки? Все на Maybe/Either, что препдологает возможность обработки.

Ну тут два варианта. Либо сразу ловить ошибку и оборачивать ее в Maybe/Either, либо кидать ошибки как попало и потом гденибудь в "outermost function" их ловить.

Пример ошибок, помимо тех, которые кидаешь ты сам (включая ексепшны от нетотальных ф-й), это ошибки http запросов. Что если `req` не сможет выполнить запрос? Приложение скорее всего просто упадет. Возможно это неисправимый баг, а возможно это просто проблемы с сетью, которые скоро пройдут, и нужно просто подождать
